"use strict";

// Generated by CoffeeScript 2.3.1
(function () {
  var G_root, Q;

  require("spinal-core-connectorjs");

  Q = require("q");

  G_root = typeof window === "undefined" ? global : window;

  module.exports = {
    modelType: G_root.Lst,
    modelName: "Lst",
    prority: 1,
    handler: function handler() {
      var _json, _model, i, len, prom, value;
      _json = this._json;
      _model = this._model;
      if (!_json.data) {
        _json.data = [];
      }
      prom = [];
      i = 0;
      len = _model.length;
      while (i < len) {
        value = _model[i];
        prom.push(G_root.JsonProcess._assignPush.call(this, _json, value));
        i++;
      }
      return Q.all(prom).then(function (data) {
        return _json;
      });
    }
  };
}).call(undefined);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9Nb2RlbEhhbmRsZXIvTHN0LmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7QUFBQSxDQUFBLFlBQUE7QUFBQSxNQUFBLE1BQUEsRUFBQSxDQUFBOztBQUFBLFVBQUEseUJBQUE7O0FBQ0EsTUFBSSxRQUFBLEdBQUEsQ0FBSjs7QUFDQSxXQUFZLE9BQUEsTUFBQSxLQUFILFdBQUcsR0FBSCxNQUFHLEdBQThDLE1BQTFEOztBQUVBLFNBQUEsT0FBQSxHQUFpQjtBQUNmLGVBQVcsT0FESSxHQUFBO0FBRWYsZUFGZSxLQUFBO0FBR2YsYUFIZSxDQUFBO0FBSWYsYUFBUyxtQkFBQTtBQUNQLFVBQUEsS0FBQSxFQUFBLE1BQUEsRUFBQSxDQUFBLEVBQUEsR0FBQSxFQUFBLElBQUEsRUFBQSxLQUFBO0FBQUEsY0FBUSxLQUFDLEtBQVQ7QUFDQSxlQUFTLEtBQUMsTUFBVjtBQUNBLFVBQW9CLENBQUksTUFBeEIsSUFBQSxFQUFBO0FBQUEsY0FBQSxJQUFBLEdBQUEsRUFBQTs7QUFDQSxhQUFPLEVBQVA7QUFDQSxVQUFJLENBQUo7QUFDQSxZQUFNLE9BQU8sTUFBYjtBQUNBLGFBQU8sSUFBUCxHQUFBLEVBQUE7QUFDRSxnQkFBUSxPQUFPLENBQVAsQ0FBUjtBQUNBLGFBQUEsSUFBQSxDQUFVLE9BQU8sV0FBUCxDQUFtQixXQUFuQixDQUFBLElBQUEsQ0FBQSxJQUFBLEVBQUEsS0FBQSxFQUFWLEtBQVUsQ0FBVjtBQUNBO0FBSEY7QUFJQSxhQUFPLEVBQUEsR0FBQSxDQUFBLElBQUEsRUFBQSxJQUFBLENBQWtCLFVBQUEsSUFBQSxFQUFBO0FBQ3ZCLGVBQU8sS0FBUDtBQURLLE9BQUEsQ0FBUDtBQVhPO0FBSk0sR0FBakI7Q0FKQSxFLElBQUEiLCJzb3VyY2VzQ29udGVudCI6WyJyZXF1aXJlKFwic3BpbmFsLWNvcmUtY29ubmVjdG9yanNcIilcblEgPSByZXF1aXJlKFwicVwiKVxuR19yb290ID0gaWYgdHlwZW9mIHdpbmRvdyA9PSBcInVuZGVmaW5lZFwiIHRoZW4gZ2xvYmFsIGVsc2Ugd2luZG93XG5cbm1vZHVsZS5leHBvcnRzID0ge1xuICBtb2RlbFR5cGU6IEdfcm9vdC5Mc3QsXG4gIG1vZGVsTmFtZTogXCJMc3RcIixcbiAgcHJvcml0eTogMVxuICBoYW5kbGVyOiAoKSAtPlxuICAgIF9qc29uID0gQF9qc29uXG4gICAgX21vZGVsID0gQF9tb2RlbFxuICAgIF9qc29uLmRhdGEgPSBbXSBpZiAobm90IF9qc29uLmRhdGEpXG4gICAgcHJvbSA9IFtdXG4gICAgaSA9IDBcbiAgICBsZW4gPSBfbW9kZWwubGVuZ3RoXG4gICAgd2hpbGUgKGkgPCBsZW4pXG4gICAgICB2YWx1ZSA9IF9tb2RlbFtpXVxuICAgICAgcHJvbS5wdXNoKEdfcm9vdC5Kc29uUHJvY2Vzcy5fYXNzaWduUHVzaC5jYWxsKEAsIF9qc29uLCB2YWx1ZSkpXG4gICAgICBpKytcbiAgICByZXR1cm4gUS5hbGwocHJvbSkudGhlbiggKGRhdGEpIC0+XG4gICAgICByZXR1cm4gX2pzb24pXG59Il0sInNvdXJjZVJvb3QiOiIuLi8uLiJ9
//# sourceURL=/home/laurent/share_to_send/modules/spinal-process-jsonprocess/src/ModelHandler/Lst.coffee