"use strict";

// Generated by CoffeeScript 2.3.1
(function () {
  var G_root;

  require("spinal-core-connectorjs");

  G_root = typeof window === "undefined" ? global : window;

  module.exports = {
    modelType: G_root.Obj,
    modelName: "Obj",
    prority: 1,
    handler: function handler() {
      this._json.data = this._model._data;
      return Promise.resolve(this._json);
    }
  };
}).call(undefined);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9Nb2RlbEhhbmRsZXIvT2JqLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7QUFBQSxDQUFBLFlBQUE7QUFBQSxNQUFBLE1BQUE7O0FBQUEsVUFBQSx5QkFBQTs7QUFDQSxXQUFZLE9BQUEsTUFBQSxLQUFILFdBQUcsR0FBSCxNQUFHLEdBQThDLE1BQTFEOztBQUVBLFNBQUEsT0FBQSxHQUFpQjtBQUNmLGVBQVcsT0FESSxHQUFBO0FBRWYsZUFGZSxLQUFBO0FBR2YsYUFIZSxDQUFBO0FBS2YsYUFBUyxtQkFBQTtBQUNQLFdBQUMsS0FBRCxDQUFBLElBQUEsR0FBYyxLQUFDLE1BQUQsQ0FBUSxLQUF0QjtBQUNBLGFBQU8sUUFBQSxPQUFBLENBQWdCLEtBQWhCLEtBQUEsQ0FBUDtBQUZPO0FBTE0sR0FBakI7Q0FIQSxFLElBQUEiLCJzb3VyY2VzQ29udGVudCI6WyJyZXF1aXJlKFwic3BpbmFsLWNvcmUtY29ubmVjdG9yanNcIilcbkdfcm9vdCA9IGlmIHR5cGVvZiB3aW5kb3cgPT0gXCJ1bmRlZmluZWRcIiB0aGVuIGdsb2JhbCBlbHNlIHdpbmRvd1xuXG5tb2R1bGUuZXhwb3J0cyA9IHtcbiAgbW9kZWxUeXBlOiBHX3Jvb3QuT2JqLFxuICBtb2RlbE5hbWU6IFwiT2JqXCIsXG4gIHByb3JpdHk6IDFcblxuICBoYW5kbGVyOiAoKSAtPlxuICAgIEBfanNvbi5kYXRhID0gQF9tb2RlbC5fZGF0YVxuICAgIHJldHVybiBQcm9taXNlLnJlc29sdmUoQF9qc29uKVxufVxuIl0sInNvdXJjZVJvb3QiOiIuLi8uLiJ9
//# sourceURL=/home/laurent/share_to_send/modules/spinal-process-jsonprocess/src/ModelHandler/Obj.coffee